### ISSUE TITLE
Broken relative path with last version v1.8.3

### ISSUE THREAD

**Issue by StudioDanton** [poucotm/Log-Highlight#10]
With previous versions, I had no problem to parse successfully and open log file with relative path like :
../../../ast/src/drivers/src_unit/man/TU_data_man.cpp:1091: failed: ...
With the last week update, instead of opening TU_data_man.cpp, it open a new empty file without taking car of ../../../ and I get this in the console :
File "Log Highlight in \Sublime Text 3\Installed Packages\Log Highlight.sublime-package", line 851, in search_base
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()

Thanks by advance to investigate this regression.

**Comment by poucotm** [comment]
Hi, I've just updated. v1.8.4, Could you check with that version?

2017. 12. 8. 오후 12:42에 "Studio Danton" <notifications@github.com>님이 작성:

**Comment by StudioDanton** [comment]
Sorry for the delay, I've encountered some difficulties to make sublime text getting your update.
The problem remains the same with version 1.8.4.
I've check with another machine still in previous version and opening file from my log are working properly.

**Comment by StudioDanton** [comment]
LOG HIGHLIGHT : ERROR _______________________________________
Traceback (most recent call last):
  File "Log Highlight in ---\Sublime Text 3\Installed Packages\Log Highlight.sublime-package", line 850, in search_base
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
=============================================================

**Comment by StudioDanton** [comment]
Traceback (most recent call last):
  File "Log Highlight in ---\Sublime Text 3\Installed Packages\Log Highlight.sublime-package", line 850, in search_base
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()

**Comment by StudioDanton** [comment]
Sorry for the delay, I'm unable to make sublime text package control getting your update.

**Comment by StudioDanton** [comment]
Sorry, I was fooled by the absence of v1.8.4.md in changelog subdir, but package-metadata.json is 1.8.4.
The problem remains the same with same error in the console.
I've check my log with another machine still in previous version and file opening are working properly.

**Comment by poucotm** [comment]
I didn't make a message for v1.8.4.
I've found the error as you stated and updated the package as v1.8.5 with a v1.8.5.md.
Thank you for letting me know.

**Comment by StudioDanton** [comment]
Everything is working great again !
Thank you very much for your wonderful plugin and your quick fix.
