### ISSUE TITLE
Error - No such file or directory: .../Packages/Log Highlight/...

### ISSUE THREAD

**Issue by mdewyer** [poucotm/Log-Highlight#42]
I've tried un/reinstalling Log Highlight a few times through the Package Manager (Sublime 3.2.2 3211) and when I try to apply "Log Highlight" (via the context menu or Command Palette) nothing happens and I get this error in the console:

```
LOG HIGHLIGHT : ERROR _______________________________________
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Roaming\Sublime Text 3\Installed Packages\Log Highlight.sublime-package\Log Highlight.py", line 653, in run
    self.run_imp()
  File "C:\Users\Matt\AppData\Roaming\Sublime Text 3\Installed Packages\Log Highlight.sublime-package\Log Highlight.py", line 692, in run_imp
    set_syntax_theme(self.view, lname)
  File "C:\Users\Matt\AppData\Roaming\Sublime Text 3\Installed Packages\Log Highlight.sublime-package\Log Highlight.py", line 198, in set_syntax_theme
    tree = plistlib.readPlist(ctheme)
  File "./python3.3/plistlib.py", line 73, in readPlist
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Matt\\AppData\\Roaming\\Sublime Text 3\\Packages\\Log Highlight/Log Highlight.tmTheme'
=============================================================
```

Indeed, the `%AppData%/Roaming/Sublime Text 3/Packages/Log Highlight` directory doesn't even exist, and never seems to be created. 

This is the log during installation:
```
ignored packages updated to: ["Log Highlight", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error parsing messages.json for Log Highlight
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Log Highlight.Log Highlight
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 196, in load_module
    m.plugin_loaded()
  File "C:\Users\Matt\AppData\Roaming\Sublime Text 3\Installed Packages\Log Highlight.sublime-package\Log Highlight.py", line 49, in plugin_loaded
    get_log_extension()
  File "C:\Users\Matt\AppData\Roaming\Sublime Text 3\Installed Packages\Log Highlight.sublime-package\Log Highlight.py", line 78, in get_log_extension
    lgl = list(lol.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
reloading settings Packages/Log Highlight/Log Highlight.sublime-settings
generating syntax summary
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Roaming\Sublime Text 3\Installed Packages\Log Highlight.sublime-package\Log Highlight.py", line 49, in plugin_loaded
TypeError: 'NoneType' object is not callable
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

If I manually create the `Log Highlight` directory and add the `Log Highlight.tmTheme` file to it, I can get it to run without the error. But I manually have to edit that file for the changes to be reflected, editing the `Log Highlight.sublime-settings` for the User doesn't do anything.

Removing from the Package Manager does correctly delete the manually-created `%AppData%/Roaming/Sublime Text 3/Packages/Log Highlight` directory.

Any ideas? Thanks!

**Comment by poucotm** [comment]
@mdewyer , Hi, I've fixed up for it (v.2.0.9). it was related with default theme position when using .subime-package. Please, check again. For installing time error, I have to look into more. Thanks.

**Comment by mdewyer** [comment]
Thanks @poucotm, I re-installed and the `./Packages/User/Log Highlight/default.tmTheme` directory and file were created successfully 👍
